name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:


  test:
    name: Test installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v4
      - name: Install
        run: bash install.sh
      - name: list
        run: ls -la
      - name: Test GIT
        run: tests/verify-git.sh
        shell: bash
      - name: Test GIT
        run: tests/verify-git.sh
        shell: zsh
