name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Test installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v4
      - name: Install
        run: bash install.sh
      - name: Test GIT
        run:
          bash tests/verify_git.sh
          zsh tests/verify_zsh.sh
