name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:


  test:
    name: Test installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v4
      - name: Install
        run: bash install.sh
      - name: list
        run: ls -la
      - name: list tests
        run: ls -la tests
      - name: Test
        run: |
          set -euo pipefail

          for f in tests/*.sh; do
            echo "Run test: $f"
            $f
          done
        shell: bash
